### PR TITLE
New entry: Blacksmith

### PR DESCRIPTION
**Pull request by adijp**

### CODE REVIEW

**Comment by neysofu** [comment]
Hey @adijp, thanks a lot for the PR!

I have provided some suggestions here: https://github.com/adijp/awesome-github-actions-runners/compare/adijp.addBlacksmith...neysofu:awesome-github-actions-runners:filippo/blacksmit-suggestions. Here's a brief summary:

- Moved Blacksmith just below WarpBuild. This is simply a reflection of how I perceive the maturity of your product offering compared with each other, and I'm happy to reevaluate in the future, possibly after some direct experience with Blacksmith.
- Modified the bullet list for some extra consistency with the other entries. Contents are mostly identical.

Please let me know if these look good! I'm a big fan of what you're doing with the Migration Wizard and I'm excited to see you push the space forward.

**Comment by adijp** [comment]
> Hey @adijp, thanks a lot for the PR!
> 
> I have provided some suggestions here: [adijp/awesome-github-actions-runners@adijp.addBlacksmith...neysofu:awesome-github-actions-runners:filippo/blacksmit-suggestions](https://github.com/adijp/awesome-github-actions-runners/compare/adijp.addBlacksmith...neysofu:awesome-github-actions-runners:filippo/blacksmit-suggestions). Here's a brief summary:
> 
> * Moved Blacksmith just below WarpBuild. This is simply a reflection of how I perceive the maturity of your product offering compared with each other, and I'm happy to reevaluate in the future, possibly after some direct experience with Blacksmith.
> * Modified the bullet list for some extra consistency with the other entries. Contents are mostly identical.
> 
> Please let me know if these look good! I'm a big fan of what you're doing with the Migration Wizard and I'm excited to see you push the space forward.

Hey @neysofu! Thanks for getting back to us. The suggestions look great. The only thing I call out:

> as well as a "**Migration Wizard**" which can automatically migrate multiple repositories at once.

Our migration wizard currently lets you migrate all the workflows from a single repo at once in a PR, but has yet to allow migrating multiple repositories at once. Just wanted to call out that distinction. Thanks!

**Comment by neysofu** [comment]
Thanks for letting me know! I fixed the description. Are you happy with me merging directly from my branch, or would you like to apply the diff to your branch so we can merge it directly from this PR? It's the same for me.

**Comment by adijp** [comment]
> Thanks for letting me know! I fixed the description. Are you happy with me merging directly from my branch, or would you like to apply the diff to your branch so we can merge it directly from this PR? It's the same for me.

Happy with you merging directly from your branch. Thanks Filippo!

**Pull request merged**
